### PR TITLE
Bug fix in LL1 table generator

### LINKED ISSUE #151: Bug in LL(1) parse table
I think there's a bug in the LL(1) parse table generation.

Example grammar to demonstrate the issue:
```
%%

S -> A;
A -> "a" | ;
```

First and follow sets are created correctly, which are:
```
First set:

┌────────┬───────────┐
│ Symbol │ First set │
├────────┼───────────┤
│ S      │ "a", ε    │
├────────┼───────────┤
│ A      │ "a", ε    │
└────────┴───────────┘

Follow set:

┌────────┬────────────┐
│ Symbol │ Follow set │
├────────┼────────────┤
│ S      │ $          │
├────────┼────────────┤
│ A      │ $          │
└────────┴────────────┘
```

However, the parse table is incorrect:
```
LL(1) parsing table:

┌───┬─────┬───┐
│   │ "a" │ $ │
├───┼─────┼───┤
│ S │ 1   │   │
├───┼─────┼───┤
│ A │ 2   │ 3 │
└───┴─────┴───┘
```

I think it should be

```
┌───┬─────┬───┐
│   │ "a" │ $ │
├───┼─────┼───┤
│ S │ 1   │ 1 │
├───┼─────┼───┤
│ A │ 2   │ 3 │
└───┴─────┴───┘
```
I think this is due to the following line 

https://github.com/DmitrySoshnikov/syntax/blob/master/src/ll/ll-parsing-table.js#L190

### PR DESCRIPTION
**Pull request by cmaglie**
In the example exposed in https://github.com/DmitrySoshnikov/syntax/issues/151:

```
%%

S -> A;
A -> "a" | ;
```

```
Parsing mode: LL(1).

Grammar:

    1. S -> A
    2. A -> 'a'
    3.    | ε
```
we get the wrong LL1 Parsing Table:

```
LL(1) parsing table:

┌───┬─────┬───┐
│   │ "a" │ $ │
├───┼─────┼───┤
│ S │ 1   │   │
├───┼─────┼───┤
│ A │ 2   │ 3 │
└───┴─────┴───┘
```

The problem is in the condition that checks the existence of ε, because a production may have other terminals besides ε.
In our case, the First(A) set equals to `"a", ε`. When we fill the table we should consider `"a"` and replace `ε` with the Follow(S) set.

After this patch we get the expected result:

```
LL(1) parsing table:

┌───┬─────┬───┐
│   │ 'a' │ $ │
├───┼─────┼───┤
│ S │ 1   │ 1 │
├───┼─────┼───┤
│ A │ 2   │ 3 │
└───┴─────┴───┘
```

Should fix #151

### CODE REVIEW

File: src/ll/ll-parsing-table.js [hunk 1]
```diff
@@ -175,20 +175,17 @@ export default class LLParsingTable {
...
-      if (keys.length === 1 && GrammarSymbol.isEpsilon(keys[0])) {
-        set = this._setsGenerator.followOf(lhs);
+      // All productions goes under the terminal column
+      // of the First(RHS) terminals.
+      let set = this._setsGenerator.firstOfRHS(rhs);
+
+      // If First(RHS) has an epsilon terminal it means
+      // that we must check also under the Follow(LHS) column.
+      // (because this production can be eliminated by epsilon).
+      if (set[EPSILON]) {
```
Comment (DmitrySoshnikov) [inline src/ll/ll-parsing-table.js:185]: Can you replace please with:
```
if (set.hasOwnProperty(EPSILON)) {
  ...
}
```

(later we may need to refactor to using  actual Set JS object instead of plain objects)

**Review by DmitrySoshnikov — COMMENTED** [review]
Looks good, thanks for fixing it! Added one comment on the code.

File: src/ll/ll-parsing-table.js (hunk 1 above)
Comment (cmaglie) [reply src/ll/ll-parsing-table.js]: Done!

**Comment by cmaglie** [comment]
> Looks good, thanks for fixing it!

Thank you for making such good courses!
